# Generated by Django 3.2.7 on 2022-05-24 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220524_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
