# Generated by Django 3.2.7 on 2022-05-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220527_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
