# Generated by Django 3.2.7 on 2022-05-24 23:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendslist',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
